version: '3.6'

services:
  
  ethnode:
    labels:
      - "traefik.docker.network=traefik_default"
      
      - "traefik.http.routers.dolce-ganache.rule=Host(`ethnode.dolce.gallery`)"
      - "traefik.http.routers.dolce-ganache.service=dolce-ganache"
      - "traefik.http.services.dolce-ganache.loadbalancer.server.port=8545"
      - "traefik.http.services.dolce-ganache.loadbalancer.healthcheck.hostname=ethnode.dolce.gallery"
    expose:
      - "8545:"
      - "8546"
      - "30303"
    networks:
      - traefik
      - dolce
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m

networks:
  traefik:
    driver: bridge
    external:
      name: traefik_default
  dolce:
    external:
      name: dolce
